prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>

SELECT ?class ?definition (group_concat(?reference) as ?references) WHERE {
  ?cls a owl:Class .
    BIND(STR(?cls) as ?class) .
  OPTIONAL { 
	?cls oio:hasDbXref ?xref
	BIND(STR(?xref) as ?reference)
  } .
  OPTIONAL { 
	?cls def: ?def 
	BIND(STR(?def) as ?definition)
  } 
}
GROUP BY ?class ?definition
