PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>  
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX oio: <http://www.geneontology.org/formats/oboInOwl#>  
PREFIX obo: <http://purl.obolibrary.org/obo/> 
        
SELECT ?label ?exact ?broad ?narrow ?related ?subset ?envo 
WHERE {
    { ?envo rdfs:label ?l 
     FILTER (regex(str(?envo), "ENVO"))
     BIND (STR(?l)  AS ?label)  
    }
    OPTIONAL{ 
        ?envo oio:hasExactSynonym ?e 
        BIND (STR(?e)  AS ?exact)  
    }
    OPTIONAL { 
        ?envo oio:hasNarrowSynonym ?n 
        BIND (STR(?n)  AS ?narrow)  
    }
    OPTIONAL { 
        ?envo oio:hasBroadSynonym ?b 
        BIND (STR(?b)  AS ?broad)  
    }
     OPTIONAL { 
        ?envo oio:hasRelatedSynonym ?r 
        BIND (STR(?r)  AS ?related)  
    }
    OPTIONAL{ 
        ?envo oio:inSubset ?subset 
    }
    FILTER NOT EXISTS {
        ?envo owl:deprecated ?bool .
    }
    
}
order by ASC(?label)